### ISSUE TITLE
Add feature to log solution iterate over different iterations 

### ISSUE THREAD

**Issue by ashishrao7** [lava-nc/lava-optimization#22] opened 2021-12-01 11:02 UTC
The current solver only returns the solution at at the last iteration. The solver needs to be enhanced by adding support for solution iterate logging in order to able to analyze cost evolution and solution convergence. Currently can be done by using a Process that behaves like an output probe. However this may not be the best way to realize this feature given that probes are being planned in future lava releases

**Comment by awintel** [comment] 2021-12-01 21:53
Be sure to keep this modular as in the case of the online constraint checker in the CSP solver. For mere probing (for debugging), we can use the Monitor going forward. For anything else that you need to run aside from diagnostic purposes you need to keep in mind that this will eventually run on neuro cores, so you should avoid reading out network state too often as in the case of the CSP offline validator.

**Comment by GaboFGuerra** [comment] 2022-01-07 09:47
Indeed, the complete design of the QP solver already includes the online validator which includes monitoring of the objective function. The online validator is shared by most solvers so it will be part of the generic processes of the optimization library. Having the ability to monitor process variables already solve this issue by just monitoring the right component of the online validator.

**Comment by GaboFGuerra** [comment] 2022-01-07 13:53
Duplicate of #26

**Comment by GaboFGuerra** [comment] 2023-01-12 18:44
@ashishrao7 should we keep this open? or we have it as a subtask of merging the QP into the generic solver?

**Comment by tim-shea** [comment] 2024-01-19 19:48
Done.

**Closed by tim-shea** 2024-01-19 19:48 UTC
Labels: 1-feature, 0-needs-review, 2-important/not-urgent
